arch: NestedUNet
batch_size: 16
dataset: GBM
deep_supervision: false
early_stopping: -1
epochs: 150
factor: 0.1
img_ext: .png
input_channels: 3
input_h: 96
input_w: 96
loss: BCEDiceLoss
lr: 0.001
mask_ext: .png
min_lr: 1.0e-05
momentum: 0.9
name: GBM_aug
nesterov: false
num_classes: 1
num_workers: 0
optimizer: SGD
patience: 2
scheduler: CosineAnnealingLR
tumor_type: GBM
use_augmentation: true
weight_decay: 0.0001
